"""The blockchain: block application, fork resolution, reorg, and persistence.

This is the consensus core.  It owns the main chain (an in-memory list of
:class:`~block.Block`), the current :class:`~state.WorldState`, and a side-branch
store used for fork handling.  Consensus follows the *heaviest chain* rule:
when two competing branches exist, the one with greater cumulative work wins,
and the node re-organises onto it (rolling back blocks below the fork point and
re-applying the winning branch).

Persistence is per-block: ``blocks/NNNNNN.json`` holds a block and
``state/NNNNNN.json`` holds the world state *after* that height, both written
atomically and mirrored by a version ledger for rollback.

Damage tolerance / quarantine
-----------------------------
A corrupt or tampered block file no longer renders the whole chain unusable.
On startup the node loads the longest *linked, hash-consistent prefix* and
exposes everything beyond it through a per-block validation report
(:meth:`scan_blocks`), distinguishing:

* ``damaged``   — the block file itself fails verification (hash/PoW/merkle/
                  signature/missing or unreadable JSON);
* ``orphan``    — a sound file whose link to the active chain is broken by a
                  damaged ancestor;
* ``state_damaged`` — block file sound, state snapshot corrupt: the snapshot is
                  deterministically regenerated by replay on boot, so healthy
                  blocks stay online.

Operators can quarantine damaged blocks (files physically moved into the
reversible :class:`~quarantine.QuarantineStore`, healthy successors marked
``detached`` and kept), after which browsing and mining continue from the last
good block. Every operation is undoable; restoring onto a diverged chain
(mining already replaced the blocks) is refused rather than overwriting data.
"""

import os
import time

from . import crypto, pow as pow_mod
from .block import Block, make_genesis_block
from .config import (COINBASE_REWARD, DIFFICULTY_ADJUST_INTERVAL,
                     GENESIS_PREV_HASH)
from .contract import ContractEngine
from .quarantine import (QuarantineStore, STATUS_DETACHED,
                         STATUS_QUARANTINED)
from .state import WorldState, ZERO_ADDRESS
from .storage import (DataPaths, VersionLedger, atomic_write_json, read_json)
from .transaction import Transaction, TX_COINBASE


# Per-block problem codes surfaced in validation reports (Chinese text is
# attached at rendering time so the same code can drive UI badges/filters).
BLOCK_ERROR_MESSAGES = {
    "FILE_MISSING": "区块文件缺失",
    "FILE_UNREADABLE": "区块文件无法解析（JSON 损坏）",
    "BLOCK_MALFORMED": "区块结构字段损坏，无法反序列化",
    "HASH_MISMATCH": "区块哈希与内容不符（区块被篡改）",
    "INDEX_MISMATCH": "区块高度与文件名/上下文不一致",
    "POW_INVALID": "工作量证明不满足难度目标",
    "MERKLE_MISMATCH": "Merkle 根与交易列表不符",
    "COINBASE_RULES": "Coinbase 交易规则被破坏（缺失/重复/位置错误）",
    "COINBASE_REWARD_MISMATCH": "Coinbase 奖励金额不符",
    "TX_SIGNATURE_INVALID": "存在签名无效的交易",
    "TX_SENDER_MISMATCH": "存在发送方与公钥不符的交易",
    "STATE_MISSING": "状态快照文件缺失",
    "STATE_UNREADABLE": "状态快照无法解析",
    "STATE_MALFORMED": "状态快照结构损坏",
    "STATE_ROOT_MISMATCH": "状态根与区块承诺不符（状态被篡改）",
    "PREV_HASH_MISMATCH": "prev_hash 与父块不匹配（链接断裂）",
    "DIFFICULTY_MISMATCH": "难度不符合调整规则",
}

# Problems that prove the block *file* itself is bad (quarantinable).
BLOCK_FILE_ERROR_CODES = {
    "FILE_MISSING", "FILE_UNREADABLE", "BLOCK_MALFORMED", "HASH_MISMATCH",
    "INDEX_MISMATCH", "POW_INVALID", "MERKLE_MISMATCH", "COINBASE_RULES",
    "COINBASE_REWARD_MISMATCH", "TX_SIGNATURE_INVALID", "TX_SENDER_MISMATCH",
}

# Problems confined to the state snapshot; a healthy block can be recovered by
# replaying transactions to regenerate the snapshot.
STATE_ERROR_CODES = {
    "STATE_MISSING", "STATE_UNREADABLE", "STATE_MALFORMED",
    "STATE_ROOT_MISMATCH",
}

# Backwards-compatible alias: all intrinsic (non-contextual) problems.
INTRINSIC_ERROR_CODES = BLOCK_FILE_ERROR_CODES | STATE_ERROR_CODES

STATUS_OK = "ok"
STATUS_DAMAGED = "damaged"
STATUS_ORPHAN = "orphan"
STATUS_MISSING = "missing"
STATUS_STATE_DAMAGED = "state_damaged"


class ChainValidationError(Exception):
    pass


def _err(code, detail=""):
    return {"code": code, "message": BLOCK_ERROR_MESSAGES.get(code, code),
            "detail": str(detail)}


class Blockchain:
    def __init__(self, cfg, paths: DataPaths):
        self.cfg = cfg
        self.paths = paths
        self.chain = []                 # main-chain blocks, index 0..height
        self.state = WorldState()
        self.fork_store = {}            # height -> list of competing blocks
        self.genesis_difficulty = float(cfg.get("INITIAL_DIFFICULTY_BITS", 16))
        self.chainwork = 0              # cumulative work of the main chain
        self.engine = ContractEngine(cfg)
        self.versions = VersionLedger(paths.versions_path)
        self.quarantine = QuarantineStore(paths)
        self.last_abandoned = []
        self.last_receipts = []
        self.startup_damage = []        # damaged heights found while booting
        self._loaded = False

    # ==================================================================== #
    # Basic accessors
    # ==================================================================== #
    @property
    def height(self):
        return len(self.chain) - 1 if self.chain else -1

    @property
    def head(self):
        return self.chain[-1] if self.chain else None

    def get_block(self, height):
        if 0 <= height < len(self.chain):
            return self.chain[height]
        return None

    def get_block_by_hash(self, hash_hex):
        for b in self.chain:
            if b.hash == hash_hex:
                return b
        for blocks in self.fork_store.values():
            for b in blocks:
                if b.hash == hash_hex:
                    return b
        return None

    def has_block(self, hash_hex):
        return self.get_block_by_hash(hash_hex) is not None

    def cumulative_work_of(self, blocks):
        return sum(int(2 ** b.difficulty) for b in blocks)

    # ==================================================================== #
    # Bootstrap / persistence
    # ==================================================================== #
    def create_genesis(self, state_root=None):
        genesis = make_genesis_block(self.genesis_difficulty, state_root)
        self.chain = [genesis]
        self.state = WorldState()
        genesis.set_state_root(self.state.root())
        genesis.recompute_hash()
        self.chainwork = int(2 ** genesis.difficulty)
        self._persist_block(genesis, self.state)
        self._write_meta()
        self.versions.record(0, genesis.hash)
        self._loaded = True
        return genesis

    def load(self):
        """Load the chain from disk (or create genesis if absent).

        Unlike a hard-fail bootstrap, this tolerates corrupt/tampered block
        files: the chain is loaded as the *linked valid prefix*, damage beyond
        it is recorded in :attr:`startup_damage` and left on disk for the
        per-block validation report / quarantine workflow.  Mining resumes from
        the tip of the valid prefix and can never overwrite the evidence.
        """
        meta = read_json(self.paths.meta_path)
        if not meta or not os.path.exists(self.paths.block_path(0)):
            self.create_genesis()
            return

        self.genesis_difficulty = float(meta.get("genesis_difficulty",
                                                 self.genesis_difficulty))
        advertised = int(meta.get("height", 0))

        # Scan every block file actually present on disk (meta may lag behind).
        on_disk = self._on_disk_heights(self.paths.blocks_dir)
        disk_max = max(on_disk) if on_disk else 0

        # Fast path: cheap linkage/hash scan to find the valid prefix.
        prefix, first_bad = self._load_valid_prefix(disk_max)
        if not prefix:
            raise ChainValidationError(
                "创世区块（height 0）文件损坏，无法启动；请从可信节点同步或重置")

        self.chain = prefix
        good_height = prefix[-1].index

        # Establish world state at the prefix tip.  A corrupt state snapshot
        # does not invalidate the (hash-consistent) block: re-apply the block
        # to regenerate it, so healthy blocks are never affected.
        self.state = self._repair_state_prefix(prefix)
        self.chainwork = self.cumulative_work_of(self.chain)

        # Record any on-disk damage beyond the prefix so the node can expose it
        # without requiring a manual "validate" click.
        if first_bad is not None:
            report = self.scan_blocks()
            self.startup_damage = [e for e in report["blocks"]
                                   if e["status"] in (STATUS_DAMAGED,
                                                      STATUS_ORPHAN,
                                                      STATUS_MISSING)]
        self._loaded = True

    @staticmethod
    def _on_disk_heights(directory):
        if not os.path.isdir(directory):
            return set()
        heights = set()
        for name in os.listdir(directory):
            try:
                heights.add(int(name.split(".")[0]))
            except ValueError:
                continue
        return heights

    def _load_valid_prefix(self, disk_max):
        """Load the longest linked, hash-consistent block prefix from disk.

        Returns ``(blocks, first_bad_height)``.  Missing/unparseable blocks or a
        broken hash link terminate the prefix.  A missing file *below* the
        highest known height is damage; a clean end-of-chain is not.
        """
        blocks = []
        prev_hash = GENESIS_PREV_HASH
        for h in range(0, disk_max + 1):
            data = read_json(self.paths.block_path(h))
            if data is None:
                return blocks, h          # gap before the chain tip
            try:
                blk = Block.from_dict(data)
            except Exception:  # noqa: BLE001 - corrupt block file
                return blocks, h
            stored_hash = data.get("header", {}).get("hash")
            recomputed = blk.header_hash()
            if stored_hash is not None and stored_hash != recomputed:
                return blocks, h
            if h > 0 and blk.prev_hash != prev_hash:
                return blocks, h
            blk.hash = recomputed
            blk.header.hash = recomputed
            blocks.append(blk)
            prev_hash = recomputed
        return blocks, None

    def _repair_state_prefix(self, blocks):
        """Load tip state for a hash-valid block prefix, repairing snapshots.

        Block files are already proven intact; any missing/corrupt/tampered
        state snapshot in the prefix is regenerated deterministically by
        replaying the block's transactions and atomically rewriting the file,
        so state-only damage never forces healthy blocks off the chain.

        Replay starts at the block *above the lowest broken snapshot*: starting
        from a later (intact) tip snapshot would leave earlier corrupt files
        unfixed.
        """
        broken_heights = set()
        for blk in blocks:
            snap = read_json(self.paths.state_path(blk.index))
            if snap is None:
                broken_heights.add(blk.index)
                continue
            try:
                candidate = WorldState.from_dict(snap)
            except Exception:  # noqa: BLE001 - corrupt snapshot
                broken_heights.add(blk.index)
                continue
            if candidate.root() != blk.header.state_root:
                broken_heights.add(blk.index)

        if not broken_heights:
            return WorldState.from_dict(
                read_json(self.paths.state_path(blocks[-1].index)))

        first_broken = min(broken_heights)
        if first_broken == 0:
            state = WorldState()
            start_index = 0
        else:
            state = WorldState.from_dict(
                read_json(self.paths.state_path(first_broken - 1)))
            start_index = first_broken
        # Replay from the first broken snapshot through the tip, rewriting
        # every snapshot on the way (broken ones and any beyond them).
        for blk in blocks[start_index:]:
            state = self.apply_block(blk, state)[0]
            atomic_write_json(self.paths.state_path(blk.index), state.to_dict())
        return state

    def _write_meta(self):
        meta = {
            "height": self.height,
            "head_hash": self.head.hash if self.head else None,
            "genesis_difficulty": self.genesis_difficulty,
            "chainwork": self.chainwork,
            "node_id": self.cfg.get("node_id", "node"),
            "updated_at": time.time(),
        }
        atomic_write_json(self.paths.meta_path, meta)

    def _persist_block(self, block, state):
        atomic_write_json(self.paths.block_path(block.index), block.to_dict())
        atomic_write_json(self.paths.state_path(block.index), state.to_dict())

    def _delete_block_files_above(self, height):
        for f in os.listdir(self.paths.blocks_dir):
            try:
                h = int(f.split(".")[0])
            except ValueError:
                continue
            if h > height:
                os.remove(os.path.join(self.paths.blocks_dir, f))
        for f in os.listdir(self.paths.state_dir):
            try:
                h = int(f.split(".")[0])
            except ValueError:
                continue
            if h > height:
                os.remove(os.path.join(self.paths.state_dir, f))

    # ==================================================================== #
    # Transaction execution
    # ==================================================================== #
    def _execute_transaction(self, tx, state, miner, height):
        """Apply a single non-coinbase transaction; return ``(ok, receipt)``.

        The state is snapshotted first so a reverting contract call undoes its
        own effects.  Fee and nonce are applied regardless of outcome (the
        attempt still consumed resources).
        """
        before = state.copy()
        receipt = {"txid": tx.txid, "ok": True, "error": None, "events": [],
                   "return": None, "transfers": [], "type": tx.tx_type,
                   "contract": None}
        try:
            if tx.tx_type == "transfer":
                if state.balance(tx.sender) < tx.amount + tx.fee:
                    raise ChainValidationError("insufficient balance")
                state.add_balance(tx.sender, -tx.amount)
                state.add_balance(tx.to, tx.amount)
            elif tx.tx_type == "deploy":
                if state.balance(tx.sender) < tx.fee:
                    raise ChainValidationError("insufficient balance for deploy")
                address = self._contract_address(tx)
                result = self.engine.deploy(
                    tx.data.get("code", ""), tx.sender, address, state,
                    constructor=tx.data.get("constructor"), height=height)
                if not result["ok"]:
                    raise ChainValidationError(result["error"] or "deploy failed")
                receipt["events"] = result["events"]
                receipt["contract"] = address
            elif tx.tx_type == "call":
                if state.balance(tx.sender) < tx.amount + tx.fee:
                    raise ChainValidationError("insufficient balance for call")
                # Credit the contract with the attached value before invoking,
                # so msg.value / this_balance / transfer see it.
                state.add_balance(tx.sender, -tx.amount)
                state.add_balance(tx.to, tx.amount)
                result = self.engine.invoke(
                    tx.to, tx.data.get("function"), tx.data.get("args", []),
                    tx.sender, tx.amount, state, height)
                if not result["ok"]:
                    raise ChainValidationError(result["error"] or "call failed")
                receipt["events"] = result["events"]
                receipt["return"] = result["return"]
                receipt["contract"] = tx.to
            else:
                raise ChainValidationError(f"unknown type {tx.tx_type}")
        except Exception as e:  # noqa: BLE001 - revert semantics
            state = before
            receipt["ok"] = False
            receipt["error"] = str(e)

        # Fee + nonce bookkeeping is applied even when the call reverted.
        if state.balance(tx.sender) >= tx.fee:
            state.add_balance(tx.sender, -tx.fee)
            state.add_balance(miner, tx.fee)
        state.increment_nonce(tx.sender)
        return state, receipt

    def _contract_address(self, tx):
        """Derive a deterministic contract address from the deploy tx."""
        return "0xc" + crypto.sha256(tx.txid.encode()).hex()[:40]

    def apply_block(self, block, state):
        """Apply all transactions of ``block`` to ``state``; return receipts."""
        miner = ZERO_ADDRESS
        receipts = []
        for tx in block.transactions:
            if tx.is_coinbase():
                miner = tx.to
                state.add_balance(tx.to, tx.amount)
                receipts.append({"txid": tx.txid, "ok": True, "coinbase": True})
                continue
            state, receipt = self._execute_transaction(
                tx, state, miner or ZERO_ADDRESS, block.index)
            receipts.append(receipt)
        return state, receipts

    # ==================================================================== #
    # Block validation
    # ==================================================================== #
    def validate_block(self, block, prev_block):
        """Full validation of ``block`` against ``prev_block``."""
        if block.index != prev_block.index + 1:
            return False, "block index is not prev+1"
        if block.prev_hash != prev_block.hash:
            return False, "prev_hash does not match parent"
        ok, reason = block.validate_structure()
        if not ok:
            return False, reason
        if block.difficulty != pow_mod.next_difficulty(self, block):
            return False, "difficulty does not match schedule"
        # Verify transaction signatures and sender authenticity.
        for tx in block.transactions:
            if tx.is_coinbase():
                if tx.amount != COINBASE_REWARD:
                    return False, "coinbase reward mismatch"
                continue
            if not tx.validate_signature():
                return False, f"invalid signature on tx {tx.txid}"
            if tx.derived_sender() != tx.sender:
                return False, f"sender mismatch on tx {tx.txid}"
        return True, "ok"

    # ==================================================================== #
    # Consensus: adding blocks, fork handling, reorg
    # ==================================================================== #
    def add_block(self, block):
        """Add a validated block, resolving any fork it creates.

        Returns ``(status, message)`` where status is one of
        ``extended``, ``duplicate``, ``stored_fork``, ``reorg``, ``invalid``.
        """
        # Duplicate protection.
        if self.has_block(block.hash):
            return "duplicate", "block already known"

        if block.index == self.height + 1:
            prev = self.get_block(block.index - 1)
            if prev is None or block.prev_hash != prev.hash:
                # Might extend a stored fork.
                return self._maybe_extend_fork(block)
            ok, reason = self.validate_block(block, prev)
            if not ok:
                return "invalid", reason
            return self._extend(block)

        if block.index <= self.height:
            return self._maybe_extend_fork(block)

        # block.index > height + 1: we are missing ancestors -> request sync.
        return "missing", "missing ancestor blocks (need sync)"

    def _apply_and_verify(self, block, state):
        """Apply ``block`` to ``state``, verifying the committed state root."""
        new_state, receipts = self.apply_block(block, state)
        if new_state.root() != block.header.state_root:
            raise ChainValidationError(
                "state root mismatch after applying block (non-deterministic "
                "or malformed block)")
        return new_state, receipts

    def _extend(self, block):
        try:
            new_state, receipts = self._apply_and_verify(block, self.state.copy())
        except ChainValidationError as e:
            return "invalid", str(e)
        self.chain.append(block)
        self.state = new_state
        self.chainwork += int(2 ** block.difficulty)
        self.last_receipts = receipts
        self._persist_block(block, new_state)
        self._write_meta()
        self.versions.record(block.index, block.hash)
        return "extended", "chain extended"

    def _maybe_extend_fork(self, block):
        """Store a competing block, and reorg if it makes a heavier branch."""
        if block.index == self.height and block.prev_hash != self.head.prev_hash:
            # A sibling of our head (or an ancestor fork we still track).
            pass
        self.fork_store.setdefault(block.index, []).append(block)

        # Try to trace a branch from this block back to the main chain.
        branch = self._trace_branch(block)
        if branch is None:
            return "stored_fork", "competing block stored (branch incomplete)"
        branch_work = self.cumulative_work_of(branch)
        main_work_at_ancestor = self.cumulative_work_of(
            self.chain[:branch[0].index + 1]) if branch else 0
        if branch_work + main_work_at_ancestor > self.chainwork:
            return self._reorg(branch)
        return "stored_fork", "competing block stored (weaker branch)"

    def _trace_branch(self, tip):
        """Walk fork_store back to a block whose parent is on the main chain."""
        by_hash = {b.hash: b for blocks in self.fork_store.values()
                   for b in blocks}
        branch = []
        current = tip
        seen = set()
        while current is not None and current.hash not in seen:
            seen.add(current.hash)
            branch.append(current)
            if current.index == 0:
                break
            # Parent on the main chain?
            main_parent = self.get_block(current.index - 1)
            if main_parent is not None and main_parent.hash == current.prev_hash:
                branch.reverse()
                return branch
            current = by_hash.get(current.prev_hash)
        return None

    def _reorg(self, branch):
        """Switch the main chain onto a heavier fork ``branch``.

        ``branch`` is a list of blocks whose first element's parent is on the
        current main chain.  Blocks after the common ancestor are rolled back
        (their state is discarded and transactions re-admitted by the caller)
        and the branch is applied in order.
        """
        ancestor_height = branch[0].index - 1
        abandoned = self.chain[ancestor_height + 1:]

        # Roll back state to the ancestor snapshot.
        ancestor_state_data = read_json(self.paths.state_path(ancestor_height))
        state = WorldState.from_dict(ancestor_state_data)
        self.chain = self.chain[:ancestor_height + 1]
        self.chainwork = self.cumulative_work_of(self.chain)
        self.last_abandoned = list(abandoned)  # for tx re-admission by the node

        applied = 0
        all_receipts = []
        for blk in branch:
            state, receipts = self.apply_block(blk, state)
            all_receipts.extend(receipts)
            if state.root() != blk.header.state_root:
                # The winning branch must itself be consistent; if not, keep
                # the current chain and flag the reorg as failed.
                return "invalid", "fork branch failed state-root verification"
            self.chain.append(blk)
            self.chainwork += int(2 ** blk.difficulty)
            self._persist_block(blk, state)
            applied += 1

        self.state = state
        self.last_receipts = all_receipts
        self._write_meta()
        self.versions.record(self.height, self.head.hash)
        # Clean fork_store of now-main blocks.
        for b in branch:
            self.fork_store.pop(b.index, None)
        return "reorg", (f"reorg at height {ancestor_height}: "
                         f"rolled back {len(abandoned)} block(s), "
                         f"applied {applied} block(s)")

    def rollback(self, target_height):
        """Roll the chain back to ``target_height`` (admin operation)."""
        if target_height < 0 or target_height >= self.height:
            return False, "invalid target height"
        if not os.path.exists(self.paths.state_path(target_height)):
            return False, "no state snapshot at target height"
        state_data = read_json(self.paths.state_path(target_height))
        self.state = WorldState.from_dict(state_data)
        self.chain = self.chain[:target_height + 1]
        self.chainwork = self.cumulative_work_of(self.chain)
        self._delete_block_files_above(target_height)
        self._write_meta()
        self.versions.record(target_height, self.head.hash)
        return True, f"rolled back to height {target_height}"

    # ==================================================================== #
    # Dashboard / display aggregation helpers
    # ==================================================================== #
    def tx_type_counts(self):
        counts = {}
        for blk in self.chain:
            for tx in blk.transactions:
                cat = tx.stats_category()
                counts[cat] = counts.get(cat, 0) + 1
        return counts

    def avg_block_interval(self, window=20):
        blocks = self.chain
        if len(blocks) < 2:
            return 0.0
        start = max(1, len(blocks) - window)
        intervals = [blocks[i].elapsed_since(blocks[i - 1])
                     for i in range(start, len(blocks))]
        return sum(intervals) / len(intervals) if intervals else 0.0

    def difficulty_series(self):
        return pow_mod.difficulty_series(self)

    def top_accounts(self, limit=10):
        return self.state.top_accounts(limit=limit)

    def balance_for_display(self, address):
        return self.state.display_balance(address)

    def chain_summary(self):
        """All blocks visible in the explorer, including isolated ones.

        Active blocks are listed by height; quarantined/detached blocks are
        appended after the active tip so their links stay visible and the
        explorer can mark them prominently.
        """
        out = [
            {
                "index": b.index, "hash": b.hash, "prev_hash": b.prev_hash,
                "timestamp": b.timestamp, "difficulty": b.difficulty,
                "tx_count": b.display_tx_count(), "nonce": b.nonce,
                "status": STATUS_OK, "quarantined": False,
            }
            for b in self.chain
        ]
        for height in sorted(self.quarantine.active_blocks()):
            rec = self.quarantine.active_blocks()[height]
            data = self.quarantine.read_block_data(height)
            active_at_height = self.get_block(height)
            entry = {
                "index": height,
                "hash": rec.get("hash"),
                "prev_hash": None,
                "timestamp": None,
                "difficulty": None,
                "tx_count": None,
                "nonce": None,
                "status": rec["status"],
                "quarantined": rec["status"] == STATUS_QUARANTINED,
                # True when a replacement block has since been mined at this
                # height: the isolated file is historical evidence, kept
                # visible but clearly separated from the live chain.
                "replaced": active_at_height is not None,
                "reason": rec.get("reason", ""),
            }
            if data is not None:
                try:
                    blk = Block.from_dict(data)
                    entry.update({
                        "hash": blk.hash, "prev_hash": blk.prev_hash,
                        "timestamp": blk.timestamp,
                        "difficulty": blk.difficulty,
                        "tx_count": blk.display_tx_count(), "nonce": blk.nonce,
                    })
                except Exception:  # noqa: BLE001 - corrupt payload
                    pass
            out.append(entry)
        return out

    def block_summary(self, block):
        return {
            "index": block.index, "hash": block.hash,
            "prev_hash": block.prev_hash, "timestamp": block.timestamp,
            "difficulty": block.difficulty,
            "tx_count": block.display_tx_count(), "nonce": block.nonce,
            "merkle_root": block.header.merkle_root,
            "state_root": block.state_root,
            "status": STATUS_OK, "quarantined": False,
        }

    def isolated_summary(self, height):
        """Summary of a quarantined/detached block at ``height`` (or None)."""
        rec = self.quarantine.get_active_block(height)
        if not rec:
            return None
        out = {
            "index": height, "hash": rec.get("hash"),
            "status": rec["status"],
            "quarantined": rec["status"] == STATUS_QUARANTINED,
            "reason": rec.get("reason", ""), "errors": rec.get("errors", []),
            "op_id": rec.get("op_id"), "block": None,
        }
        data = self.quarantine.read_block_data(height)
        if data is not None:
            try:
                out["block"] = Block.from_dict(data).to_dict()
            except Exception as e:  # noqa: BLE001 - corrupt payload
                out["parse_error"] = str(e)
        else:
            out["parse_error"] = "区块文件缺失或已损坏到无法解析"
        return out

    def get_any_block(self, identifier):
        """Find an active block first, then an isolated one (by height/hash).

        For a height lookup where an isolated record exists *and* no active
        block occupies the same height, the isolated copy wins so the explorer
        can show it.  When mining has produced a replacement at the same
        height, the active replacement wins and the isolated copy stays
        reachable by hash.
        """
        if isinstance(identifier, str) and identifier.isdigit():
            identifier = int(identifier)
        if isinstance(identifier, int):
            block = self.get_block(identifier)
            if block:
                return block, STATUS_OK
            rec = self.quarantine.get_active_block(identifier)
            if rec:
                data = self.quarantine.read_block_data(identifier)
                if data is not None:
                    try:
                        return Block.from_dict(data), rec["status"]
                    except Exception:  # noqa: BLE001
                        return None, rec["status"]
                return None, rec["status"]
            return None, None
        block = self.get_block_by_hash(identifier)
        if block:
            return block, STATUS_OK
        for height, rec in self.quarantine.active_blocks().items():
            if rec.get("hash") == identifier:
                data = self.quarantine.read_block_data(height)
                if data is not None:
                    try:
                        return Block.from_dict(data), rec["status"]
                    except Exception:  # noqa: BLE001
                        return None, rec["status"]
                return None, rec["status"]
        return None, None

    def transactions_for(self, address, limit=200):
        txs = []
        for blk in self.chain:
            for tx in blk.transactions:
                if tx.involves(address):
                    txs.append({
                        "txid": tx.txid, "type": tx.tx_type, "from": tx.sender,
                        "to": tx.to, "amount": tx.amount, "fee": tx.fee,
                        "nonce": tx.nonce, "height": blk.index,
                        "timestamp": tx.timestamp,
                    })
        txs.reverse()
        return txs[:limit]

    # ==================================================================== #
    # Tamper detection: per-block deep validation & scanning
    # ==================================================================== #
    def _check_block_payload(self, block, genesis_ok=False):
        """Intrinsic checks on a parsed block (no chain context needed).

        Returns a list of error dicts: hash/PoW/merkle/coinbase/signatures.
        Genesis is exempt from PoW.
        """
        errors = []
        stored_hash = block.hash
        recomputed = block.header_hash()
        if stored_hash and stored_hash != recomputed:
            errors.append(_err("HASH_MISMATCH",
                               f"存储哈希 {str(stored_hash)[:16]}… / "
                               f"重算 {recomputed[:16]}…"))
        block.hash = recomputed
        block.header.hash = recomputed

        if not (genesis_ok and block.index == 0):
            if not block.check_pow():
                errors.append(_err(
                    "POW_INVALID",
                    f"哈希 {recomputed[:16]}… 不满足难度 "
                    f"{block.difficulty} 的目标值"))
        if block.merkle_root() != block.header.merkle_root:
            errors.append(_err("MERKLE_MISMATCH"))

        coinbases = [tx for tx in block.transactions if tx.is_coinbase()]
        if len(coinbases) > 1:
            errors.append(_err("COINBASE_RULES", "区块内存在多个 coinbase 交易"))
        elif coinbases and block.transactions[0] is not coinbases[0]:
            errors.append(_err("COINBASE_RULES",
                               "coinbase 交易必须是区块第一笔交易"))
        for tx in block.transactions:
            if tx.is_coinbase():
                if tx.amount != COINBASE_REWARD:
                    errors.append(_err(
                        "COINBASE_REWARD_MISMATCH",
                        f"tx {tx.txid[:16]}… 奖励 {tx.amount} ≠ "
                        f"{COINBASE_REWARD}"))
                continue
            try:
                if not tx.validate_signature():
                    errors.append(_err("TX_SIGNATURE_INVALID",
                                       f"tx {tx.txid[:16]}…"))
                elif tx.derived_sender() != tx.sender:
                    errors.append(_err("TX_SENDER_MISMATCH",
                                       f"tx {tx.txid[:16]}…"))
            except Exception as e:  # noqa: BLE001 - malformed transaction
                errors.append(_err("TX_SIGNATURE_INVALID",
                                   f"tx {getattr(tx, 'txid', '?')[:16]}…: {e}"))
        return errors

    def _check_state_snapshot(self, block):
        """Validate the on-disk state snapshot committed by ``block``."""
        snap = read_json(self.paths.state_path(block.index))
        if snap is None:
            if os.path.exists(self.paths.state_path(block.index)):
                return [_err("STATE_UNREADABLE")]
            return [_err("STATE_MISSING")]
        try:
            stored_state = WorldState.from_dict(snap)
        except Exception as e:  # noqa: BLE001
            return [_err("STATE_MALFORMED", str(e))]
        if stored_state.root() != block.header.state_root:
            return [_err("STATE_ROOT_MISMATCH",
                         f"快照根 {str(stored_state.root())[:16]}… / "
                         f"承诺根 {str(block.header.state_root)[:16]}…")]
        return []

    def _check_block_on_disk(self, height, prev_block):
        """Run all applicable checks against the block file at ``height``.

        Returns ``(block_or_none, errors)`` where ``block`` is the parsed block
        when the file was parseable.
        """
        errors = []
        path = self.paths.block_path(height)
        data = read_json(path)
        if data is None:
            if os.path.exists(path):
                return None, [_err("FILE_UNREADABLE")]
            return None, [_err("FILE_MISSING")]
        try:
            block = Block.from_dict(data)
        except Exception as e:  # noqa: BLE001
            return None, [_err("BLOCK_MALFORMED", str(e))]

        header = data.get("header", {})
        if header.get("index") != height:
            errors.append(_err("INDEX_MISMATCH",
                               f"文件高度 {height}，头内高度 {header.get('index')}"))
        errors.extend(self._check_block_payload(
            block, genesis_ok=(height == 0)))

        # Contextual checks need a valid parent.
        if prev_block is not None:
            if block.prev_hash != prev_block.hash:
                errors.append(_err(
                    "PREV_HASH_MISMATCH",
                    f"指向 {str(block.prev_hash)[:16]}…，父块实际为 "
                    f"{str(prev_block.hash)[:16]}…"))
            if not self._difficulty_ok(block, prev_block):
                errors.append(_err(
                    "DIFFICULTY_MISMATCH",
                    f"区块难度 {block.difficulty} 不符合难度调整规则"))

        errors.extend(self._check_state_snapshot(block))
        return block, errors

    def _difficulty_ok(self, block, prev_block):
        """Whether ``block``'s difficulty matches the schedule.

        For orphan blocks (active-chain gaps), the retarget *start* block may be
        unavailable; in that case only "carries parent difficulty" (the common
        case at non-boundary heights) can be checked.
        """
        expected = None
        if block.index % DIFFICULTY_ADJUST_INTERVAL == 0:
            start = self.get_block(block.index - DIFFICULTY_ADJUST_INTERVAL)
            if start is not None and not (start.index == 0
                                          and start.timestamp == 0):
                expected = pow_mod.adjust_difficulty(
                    prev_block.difficulty, block.timestamp - start.timestamp)
        if expected is None:
            expected = prev_block.difficulty
        return abs(float(block.difficulty) - float(expected)) < 1e-9

    def scan_blocks(self):
        """Inspect every known block: active chain, raw tail, and quarantine.

        Produces the per-block report used by the admin UI.  Each entry is::

            {height, status ("ok"|"damaged"|"orphan"|"missing"
                             |"quarantined"|"detached"),
             hash, intrinsic (bool), errors: [{code,message,detail}],
             note}
        """
        entries = []

        # ---- active chain (deep re-verification of the loaded prefix) ----
        prev = None
        for blk in self.chain:
            errors = self._check_block_payload(
                blk, genesis_ok=(blk.index == 0))
            if prev is not None:
                if blk.prev_hash != prev.hash:
                    errors.append(_err("PREV_HASH_MISMATCH"))
                if not self._difficulty_ok(blk, prev):
                    errors.append(_err("DIFFICULTY_MISMATCH"))
            errors.extend(self._check_state_snapshot(blk))
            # Compare the in-memory block against the current on-disk file:
            # a mismatch means the file was tampered with after the node
            # booted (or was already corrupt and skipped during tolerant load).
            disk_data = read_json(self.paths.block_path(blk.index))
            if disk_data is None:
                errors.append(_err("FILE_MISSING"))
            else:
                try:
                    disk_blk = Block.from_dict(disk_data)
                    if disk_blk.header_hash() != blk.header.hash:
                        errors.append(_err(
                            "HASH_MISMATCH",
                            "磁盘文件哈希与已加载区块不一致（文件被外部篡改？）"))
                except Exception as e:  # noqa: BLE001
                    errors.append(_err("BLOCK_MALFORMED", str(e)))
            block_file_bad = any(e["code"] in BLOCK_FILE_ERROR_CODES
                                 for e in errors)
            state_bad = any(e["code"] in STATE_ERROR_CODES for e in errors)
            if block_file_bad:
                status = STATUS_DAMAGED
            elif state_bad:
                status = STATUS_STATE_DAMAGED
            elif errors:
                status = "context_error"
            else:
                status = STATUS_OK
            entries.append({
                "height": blk.index,
                "status": status,
                "hash": blk.hash,
                "intrinsic": block_file_bad or state_bad,
                "errors": errors,
                "location": "active",
            })
            prev = blk

        active_heights = {b.index for b in self.chain}
        on_disk = self._on_disk_heights(self.paths.blocks_dir)
        disk_max = max(on_disk) if on_disk else self.height

        # ---- raw files above the active prefix (damage zone) ----
        prev_good = self.chain[-1] if self.chain else None
        for h in range(self.height + 1, disk_max + 1):
            if h in active_heights:
                continue
            block, errors = self._check_block_on_disk(h, prev_good)
            codes = {e["code"] for e in errors}
            file_bad = bool(codes & BLOCK_FILE_ERROR_CODES)
            state_bad = bool(codes & STATE_ERROR_CODES)
            if not errors:
                status = STATUS_OK
            elif codes == {"FILE_MISSING"}:
                status = STATUS_MISSING
            elif file_bad:
                status = STATUS_DAMAGED
            elif state_bad:
                # Block file is sound: its state snapshot can be regenerated;
                # the reason it is not on the active chain is simply that its
                # ancestors broke — report it as an orphaned but salvageable.
                status = STATUS_ORPHAN
            else:
                status = STATUS_ORPHAN
            entries.append({
                "height": h, "status": status,
                "hash": block.hash if block is not None else None,
                "intrinsic": file_bad, "errors": errors,
                "location": "active",
            })
            # A healthy file can serve as parent for the next file; a damaged
            # one cannot, so linkage stays broken from here on.
            if block is not None and status != STATUS_DAMAGED:
                prev_good = block

        # Heights referenced by quarantine but absent anywhere are still gaps.
        known_heights = set(range(0, disk_max + 1))

        # ---- quarantine store ----
        for height in sorted(self.quarantine.active_blocks()):
            rec = self.quarantine.get_active_block(height)
            if height in known_heights:
                continue
            entries.append({
                "height": height,
                "status": (STATUS_QUARANTINED if rec["status"] ==
                           STATUS_QUARANTINED else STATUS_DETACHED),
                "hash": rec.get("hash"),
                "intrinsic": rec["status"] == STATUS_QUARANTINED,
                "errors": [{"code": "QUARANTINED",
                            "message": "已隔离的损坏区块",
                            "detail": rec.get("reason", "")}]
                if rec["status"] == STATUS_QUARANTINED else
                [{"code": "DETACHED",
                  "message": "因上游损坏而脱落的区块（文件本身完好）",
                  "detail": rec.get("reason", "")}],
                "location": "quarantine",
                "op_id": rec.get("op_id"),
                "quarantined_at": next(
                    (o["time"] for o in self.quarantine.list_operations()
                     if o["id"] == rec.get("op_id")), None),
            })

        entries.sort(key=lambda e: e["height"])
        damaged = [e for e in entries if e["status"] == STATUS_DAMAGED]
        state_damaged = [e for e in entries
                         if e["status"] == STATUS_STATE_DAMAGED]
        orphans = [e for e in entries if e["status"] == STATUS_ORPHAN]
        missing = [e for e in entries if e["status"] == STATUS_MISSING]
        isolated = [e for e in entries if e["status"] in
                    (STATUS_QUARANTINED, STATUS_DETACHED)]
        problem_statuses = (STATUS_DAMAGED, STATUS_ORPHAN, STATUS_MISSING,
                            STATUS_STATE_DAMAGED)
        report = {
            "valid": not (damaged or state_damaged or orphans or missing),
            "chain_usable": not (damaged or orphans or missing),
            "checked": len(entries),
            "active_height": self.height,
            "damaged_count": len(damaged),
            "state_damaged_count": len(state_damaged),
            "orphan_count": len(orphans),
            "isolated_count": len(isolated),
            "blocks": entries,
            # Flat string list kept for backwards compatibility with older UI.
            "errors": [
                f"height {e['height']}: " +
                "; ".join(f"{x['message']}（{x['detail']}）"
                          if x.get("detail") else x["message"]
                          for x in e["errors"])
                for e in entries if e["errors"] and
                e["status"] in problem_statuses
            ],
        }
        return report

    def validate_full_chain(self):
        """Re-verify every block (including raw/quarantined files) on disk."""
        return self.scan_blocks()

    # ==================================================================== #
    # Quarantine workflow (plan -> confirm -> isolate -> undo)
    # ==================================================================== #
    def unprocessed_damage(self):
        """Damaged/orphan raw files still sitting on the active chain path.

        While these exist the chain must not mine (a new block file could
        overwrite evidence), so mining is gated on this being empty.
        """
        return [e for e in self.scan_blocks()["blocks"]
                if e["status"] in (STATUS_DAMAGED, STATUS_ORPHAN,
                                   STATUS_MISSING)]

    def quarantine_plan(self, heights):
        """Preview what isolating ``heights`` would do (no mutation).

        Returns a dict describing the exact operation, so the UI can ask for
        informed confirmation.
        """
        report = self.scan_blocks()
        by_height = {e["height"]: e for e in report["blocks"]}
        selected = sorted(int(h) for h in heights)
        if not selected:
            return None, "未选择任何区块"
        bad = [h for h in selected if by_height.get(h, {}).get("status")
               != STATUS_DAMAGED]
        if bad:
            return None, ("只能隔离经校验确认损坏（intrinsic）的区块，"
                          f"以下高度不符合：{', '.join('#' + str(h) for h in bad)}")
        if 0 in selected:
            return None, "创世区块不能被隔离"

        first = selected[0]
        # All damaged blocks at/above the first selection must be included;
        # otherwise the active chain would keep pointing at corrupt data.
        required = sorted(e["height"] for e in report["blocks"]
                          if e["status"] == STATUS_DAMAGED
                          and e["height"] >= first)
        missing_sel = [h for h in required if h not in selected]
        if missing_sel:
            return None, ("选择的隔离点以下仍有损坏块，必须一并隔离："
                          + ", ".join("#" + str(h) for h in missing_sel))

        # Everything at/above the first selected height leaves the chain.
        affected = [e for e in report["blocks"]
                    if e["height"] >= first and
                    e["location"] == "active"]
        quarantined = [e for e in affected if e["status"] == STATUS_DAMAGED]
        detached = [e for e in affected if e["status"] != STATUS_DAMAGED]
        truncate_height = first - 1
        return {
            "heights": selected,
            "truncate_height": truncate_height,
            "quarantined": [self._plan_entry(e) for e in quarantined],
            "detached": [self._plan_entry(e) for e in detached],
            "quarantine_count": len(quarantined),
            "detach_count": len(detached),
        }, None

    @staticmethod
    def _plan_entry(entry):
        return {
            "height": entry["height"],
            "status": entry["status"],
            "hash": entry.get("hash"),
            "reason": "; ".join(x["message"] for x in entry.get("errors", [])),
            "errors": entry.get("errors", []),
        }

    def quarantine_blocks(self, heights, note=""):
        """Isolate selected damaged blocks (must match :meth:`quarantine_plan`).

        Returns ``(op, None)`` or ``(None, error)``.  Healthy blocks above the
        first isolation point are *detached* (kept, restorable).
        """
        plan, err = self.quarantine_plan(heights)
        if err:
            return None, err
        truncate_height = plan["truncate_height"]
        op = self.quarantine.create_operation(
            plan["quarantined"], plan["detached"], truncate_height, note=note)
        self._reload_after_isolation(truncate_height)
        self.startup_damage = []
        return op, None

    def _reload_after_isolation(self, truncate_height):
        """Re-establish chain/state on the linked prefix below the damage."""
        prefix = self.chain[:truncate_height + 1]
        state = self._repair_state_prefix(prefix)
        self.chain = prefix
        self.state = state
        self.chainwork = self.cumulative_work_of(prefix)
        self.fork_store = {h: v for h, v in self.fork_store.items()
                           if h <= truncate_height}
        self._write_meta()
        self.versions.record(truncate_height, self.head.hash,
                             {"action": "quarantine"})

    def restore_operation(self, op_id):
        """Undo a quarantine operation and reload the restored chain.

        Returns ``(heights, residual_damage_heights)``.  Refuses only when
        current block/state files would be overwritten (e.g. mining already
        produced replacement blocks).  Files are restored verbatim; if they
        were still corrupt the chain simply loads the valid prefix again and
        the residual damage is reported in the second return value so the
        caller can re-run validation / quarantine.
        """
        ok, msg, heights = self.quarantine.undo_operation(
            op_id, expected_tip=self.height)
        if not ok:
            return None, None, msg

        on_disk = self._on_disk_heights(self.paths.blocks_dir)
        disk_max = max(on_disk) if on_disk else 0
        prefix, first_bad = self._load_valid_prefix(disk_max)
        if not prefix:
            return None, None, "恢复后无法加载链（创世块异常）"
        self.chain = prefix
        self.state = self._repair_state_prefix(prefix)
        self.chainwork = self.cumulative_work_of(prefix)
        residual = []
        if first_bad is not None:
            residual = sorted({e["height"]
                               for e in self.scan_blocks()["blocks"]
                               if e["status"] in (STATUS_DAMAGED,
                                                  STATUS_ORPHAN,
                                                  STATUS_MISSING)})
            self.startup_damage = [e for e in self.scan_blocks()["blocks"]
                                   if e["status"] in (STATUS_DAMAGED,
                                                      STATUS_ORPHAN,
                                                      STATUS_MISSING)]
        else:
            self.startup_damage = []
        self._write_meta()
        self.versions.record(self.height, self.head.hash,
                             {"action": "quarantine_undo"})
        return heights, residual, None

    def quarantine_operations(self):
        """All quarantine operations (active and undone) for the admin UI."""
        ops = []
        for op in self.quarantine.list_operations():
            ops.append({
                "id": op["id"], "time": op["time"], "active": op["active"],
                "truncate_height": op.get("truncate_height"),
                "note": op.get("note", ""),
                "quarantine_count": sum(1 for b in op["blocks"]
                                        if b["status"] == STATUS_QUARANTINED),
                "detach_count": sum(1 for b in op["blocks"]
                                    if b["status"] == STATUS_DETACHED),
                "heights": [b["height"] for b in op["blocks"]],
                "undone_at": op.get("undone_at"),
            })
        return ops
